name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  NEXT_TELEMETRY_DISABLED: "1"
  NO_UPDATE_NOTIFIER: "1"
  ADBLOCK: "1"
  DISABLE_OPENCOLLECTIVE: "1"
  CI: "true"
  npm_config_update_notifier: "false"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Enable Corepack
        run: corepack enable || true

      - name: Install, Build, Lint (Zero-Network)
        run: bash scripts/ci-build.sh